spring.application.name=fingenie-ai

spring.datasource.url=jdbc:mysql://localhost:3306/fingenie_db
spring.datasource.username=root
spring.datasource.password=FarooqAdmin@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fingenieai.bank@gmail.com
spring.mail.password=giop yxih elqf zhoj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


# Console logging format
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] %c{1} - %msg%n

# File logging
logging.file.name=logs/fingenie.log

# File log format
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%level] %c{2} [%t] : %msg%n

# Log levels
logging.level.root=INFO
logging.level.com.fingenie=INFO



# JWT
app.jwt.secret=FingenieSecretKeyForJwtAuthentication2026SecureKey
app.jwt.expiration-ms=86400000
app.cors.allowed-origin=http://localhost:5173
app.loan-service.base-url=http://localhost:8081/loans
app.otp.expiration-minutes=5

